-- Infinity Network / InfiNet community chat
-- Run this once in the Supabase SQL Editor.

create table if not exists public.chat_users (
  user_id uuid primary key default gen_random_uuid(),
  username text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_sessions (
  session_id text primary key,
  user_id uuid not null references public.chat_users(user_id) on delete cascade,
  username text not null,
  expires_at timestamptz not null,
  last_seen timestamptz not null default now()
);

create table if not exists public.chat_messages (
  message_id bigint generated by default as identity primary key,
  user_id uuid not null references public.chat_users(user_id) on delete cascade,
  username text not null,
  content text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists chat_sessions_last_seen_idx on public.chat_sessions(last_seen);
create index if not exists chat_sessions_expires_idx on public.chat_sessions(expires_at);
create index if not exists chat_messages_created_idx on public.chat_messages(created_at desc);

alter table public.chat_users enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;

-- The FastAPI server uses the Supabase secret key. The browser never receives it.
